### ISSUE TITLE
Archived Dependency: laminas/laminas-crypt in laminas/laminas-oauth Needs Replacement

### ISSUE THREAD

**Issue by cod43156** [laminas/laminas-oauth#24]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

The laminas/laminas-crypt dependency utilized in laminas/laminas-oauth has been archived, which raises concerns about its continued support and maintenance. As laminas/laminas-crypt is deprecated, it is crucial to transition to more sustainable solutions.

**Comment by nishant04412** [comment]
@gsteel The laminas/laminas-crypt dependency utilized in laminas/laminas-oauth has been archived, which raises concerns about its continued support and maintenance. As laminas/laminas-crypt is deprecated, it is crucial to transition to more sustainable solutions.

Now suggested alternative [league/oauth1-client](https://github.com/thephpleague/oauth1-client) is also not actively maintained so we don't have much option and to use this repo only. Can you please suggest if laminas-crypt can be removed from this repo so we can get rid of laminas-crypt completely ?

**Comment by gsteel** [comment]
If it is possible to replace laminas-crypt usage with something else, then a patch would be considered.
