### ISSUE TITLE
Where is the documentation folder?

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-oauth#5]
The README.md says "follow the instructions in the documentation folder", but where is this folder?

---

Originally posted by @stavarengo at https://github.com/zendframework/ZendOAuth/issues/22

**Comment by grobokop** [comment]
It seems like you may use documentation from https://framework.zend.com/manual/1.12/en/zend.oauth.introduction.html here.
Of course you need to change class names to respect new package.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [league/oauth1-client](https://github.com/thephpleague/oauth1-client)
